# docker-compose.yml

# docker-compose version
version: "3.9"

services: 
  db: 
    container_name: budget_buddy_db
    image: "postgres:13" 
    volumes:
      - data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=budget_buddy_db
    ports:
      - "5432:5432"
      
  web:
    container_name: budget_buddy_web
    build: . 
    command: python manage.py runserver 0.0.0.0:8000 
    volumes:
      - .:/code
    ports: 
      - "8000:8000"
    depends_on: 
      - db

volumes: 
  data: